"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['ltohistory_gui.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': True}

setup(
    app=APP,
    author="Edson Cudjoe",
    author_email='e.cudjoe@hotmail.co.uk',
    date='6-Aug-2015',
    description='Calculates amount of files archived to LTO',
    name='LTO Archive History',
    url='https://github.com/edsoncudjoe/ltohistory-gui',
    version='1.1',
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
